apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.affiliateAdminV2Service.name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.affiliateAdminV2Service.name }}-dep
  minReplicas: {{ default 1 .Values.affiliateAdminV2Service.autoscaling.minReplicas }}
  maxReplicas: {{ default 3 .Values.affiliateAdminV2Service.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 60 .Values.affiliateAdminV2Service.autoscaling.targetCPUUtilizationPercentage }}
